source 'https://cdn.cocoapods.org/'

# ignore all warnings from all pods
inhibit_all_warnings!

use_frameworks!
platform :osx, '10.6'

pre_install do |installer|
  puts "prebuild kotlin frameworks to correct integration by CocoaPods..."
  puts "prebuild mpp-library..."
  `cd .. && ./gradlew :sample:mpp-library:syncMultiPlatformLibraryDebugFrameworkMacosX64`
  puts "prebuild mpp-hierarhical..."
  `cd .. && ./gradlew :sample:mpp-hierarhical:podspec`
  puts "prebuild completed"
end

target 'TestProj' do
  pod 'MultiPlatformLibrary', :path => '../mpp-library'
end

target 'TestHierarhical' do
  pod 'mpp_hierarhical', :path => '../mpp-hierarhical'
end