source 'https://cdn.cocoapods.org/'

# ignore all warnings from all pods
inhibit_all_warnings!

use_frameworks!
platform :osx, '10.6'

pre_install do |installer|
  # We represent a Kotlin/Native module to CocoaPods as a vendored framework.
  # CocoaPods needs access to such frameworks during installation process to obtain
  # their type (static or dynamic) and configure the Xcode project accordingly.
  # Build MultiPlatformLibrary framework to correct install Pod
  puts "prepare MultiPlatformLibrary.framework (require some time...)"
  `cd .. && ./gradlew :sample:mpp-library:syncMultiPlatformLibraryDebugFrameworkMacosX64`
  puts "preparing MultiPlatformLibrary.framework complete"
end

target 'TestProj' do
  pod 'MultiPlatformLibrary', :path => '../mpp-library'
end

target 'TestHierarhical' do
  pod 'mpp_hierarhical', :path => '../mpp-hierarhical'
end